### ISSUE TITLE
Python MIP

### ISSUE THREAD

**Issue by jGaboardi** [cdeil/python-discrete-optimization-examples#1]
I would also point you to the relatively new [Python MIP](https://www.python-mip.com). Here are some other links:
* [docs](https://python-mip.readthedocs.io/en/latest/)
* [PyPI](https://pypi.org/project/mip/)
* [GitHub](https://github.com/coin-or/python-mip)

**Comment by cdeil** [comment]
@jGaboardi  - Thanks for the tip!

I added minimal information for now: https://github.com/cdeil/python-discrete-optimization-examples/tree/master/mip

Will check it out in the next days ...
